<?php
/*
DO NOT EDIT THIS FILE
This file is managed by Vanilla. It is completely erased
and rebuilt when extensions are added to or removed from
the system.
*/
include($Configuration["EXTENSIONS_PATH"]."Timer.php");
include($Configuration["EXTENSIONS_PATH"]."Style.php");
include($Configuration["EXTENSIONS_PATH"]."TextMode.php");
include($Configuration["EXTENSIONS_PATH"]."DiscussionFilters.php");
include($Configuration["EXTENSIONS_PATH"]."SavedSearches.php");
include($Configuration["EXTENSIONS_PATH"]."Discovery.php");
include($Configuration["EXTENSIONS_PATH"]."CommentProtection.php");
include($Configuration["EXTENSIONS_PATH"]."Atom.php");
include($Configuration["EXTENSIONS_PATH"]."RSS2.php");
include($Configuration["EXTENSIONS_PATH"]."PanelLists.php");
include($Configuration["EXTENSIONS_PATH"]."Legends.php");
include($Configuration["EXTENSIONS_PATH"]."HtmlFormatter.php");
include($Configuration["EXTENSIONS_PATH"]."YellowFade.php");
include($Configuration["EXTENSIONS_PATH"]."PreviewPost.php");
?>