<?php
/*
DO NOT EDIT THIS FILE
This file is managed by Vanilla. It is completely erased
and rebuilt when the language is defined.
*/
include($Configuration["LANGUAGES_PATH"]."English.php");
include($Configuration["APPLICATION_PATH"]."conf/English.php");
?>