<?php
/*
 Note: this is a "-dist" file. You must create a copy of this file without the
 "-dist" in the filename for your installation.
 
 DO NOT EDIT THIS FILE
 This file is managed by Vanilla. It is completely erased and rebuilt when
 extensions are added to or removed from the system.
*/
include($Configuration["LANGUAGES_PATH"]."English.php");
include($Configuration["APPLICATION_PATH"]."conf/English.php");
?>